ERROR - 2023-04-01 21:19:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root@localhost'@'localhost' (using password: NO) in C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('p:127.0.0.1', 'root@localhost', Object(SensitiveParameterValue), 'barbearia', 3306, '', 0)
#1 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(true)
#2 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xamppp\htdocs\Barbearia-CodeIgniter\app\Controllers\Home.php(7): CodeIgniter\Database\BaseConnection->query('SELECT id FROM ...')
#4 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(312): include_once('C:\\xamppp\\htdoc...')
#5 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xamppp\\htdoc...')
#6 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#7 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#8 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(892): class_exists('\\App\\Controller...', true)
#9 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
#10 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xamppp\htdocs\Barbearia-CodeIgniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(true)
#1 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xamppp\htdocs\Barbearia-CodeIgniter\app\Controllers\Home.php(7): CodeIgniter\Database\BaseConnection->query('SELECT id FROM ...')
#3 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(312): include_once('C:\\xamppp\\htdoc...')
#4 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xamppp\\htdoc...')
#5 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#6 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#7 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(892): class_exists('\\App\\Controller...', true)
#8 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
#9 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xamppp\htdocs\Barbearia-CodeIgniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-04-01 21:19:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(7): CodeIgniter\Database\BaseConnection->query('SELECT id FROM produto')
 3 SYSTEMPATH\Autoloader\Autoloader.php(312): include_once('APPPATH\\Controllers\\Home.php')
 4 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 5 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 6 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 7 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 8 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-04-01 21:19:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'localhost'@'localhost' (using password: NO) in C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('p:127.0.0.1', 'localhost', Object(SensitiveParameterValue), 'barbearia', 3306, '', 0)
#1 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(true)
#2 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xamppp\htdocs\Barbearia-CodeIgniter\app\Controllers\Home.php(7): CodeIgniter\Database\BaseConnection->query('SELECT id FROM ...')
#4 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(312): include_once('C:\\xamppp\\htdoc...')
#5 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xamppp\\htdoc...')
#6 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#7 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#8 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(892): class_exists('\\App\\Controller...', true)
#9 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
#10 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xamppp\htdocs\Barbearia-CodeIgniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'****' (using password: NO) in C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(true)
#1 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xamppp\htdocs\Barbearia-CodeIgniter\app\Controllers\Home.php(7): CodeIgniter\Database\BaseConnection->query('SELECT id FROM ...')
#3 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(312): include_once('C:\\xamppp\\htdoc...')
#4 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xamppp\\htdoc...')
#5 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#6 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#7 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(892): class_exists('\\App\\Controller...', true)
#8 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
#9 C:\xamppp\htdocs\Barbearia-CodeIgniter\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xamppp\htdocs\Barbearia-CodeIgniter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-04-01 21:19:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'****' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(7): CodeIgniter\Database\BaseConnection->query('SELECT id FROM produto')
 3 SYSTEMPATH\Autoloader\Autoloader.php(312): include_once('APPPATH\\Controllers\\Home.php')
 4 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 5 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 6 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 7 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 8 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-04-01 21:34:16 --> Class "App\Controllers\ProdutoModel" not found
in APPPATH\Controllers\Home.php on line 6.
 1 SYSTEMPATH\Autoloader\Autoloader.php(312): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-04-01 21:34:20 --> Class "App\Controllers\ProdutoModel" not found
in APPPATH\Controllers\Home.php on line 6.
 1 SYSTEMPATH\Autoloader\Autoloader.php(312): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-04-01 21:34:24 --> Class "App\Controllers\ProdutoModel" not found
in APPPATH\Controllers\Home.php on line 6.
 1 SYSTEMPATH\Autoloader\Autoloader.php(312): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-04-01 21:38:34 --> Class "App\Controllers\ProdutoModel" not found
in APPPATH\Controllers\Home.php on line 6.
 1 SYSTEMPATH\Autoloader\Autoloader.php(312): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-04-01 21:42:32 --> Class "App\Controllers\ProdutoModel" not found
in APPPATH\Controllers\Home.php on line 6.
 1 SYSTEMPATH\Autoloader\Autoloader.php(312): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-04-01 21:47:03 --> syntax error, unexpected token "if"
in APPPATH\Controllers\Home.php on line 8.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 4 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 5 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-04-01 21:47:14 --> Object of class mysqli_result could not be converted to string
in APPPATH\Controllers\Home.php on line 9.
 1 SYSTEMPATH\Autoloader\Autoloader.php(312): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('APPPATH\\Controllers\\Home.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Home')
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Home')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\Home', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
